### PR TITLE
[FB] Split View | Add split view resizer

### PR DESCRIPTION
**Pull request by TheChilledBuffalo**
### Check list

- [ ] Referenced all related issues
- [x] Have tested the modifications
- [x] Allow Floorp to use the modifications under the Floorp Shared Source License and MIT License

### CODE REVIEW

**Comment by Ryosuke-Asano** [comment]
Great. i will review yout pr

**Comment by Ryosuke-Asano** [comment]
@TheChilledBuffalo Great. Your codes are simple. It is easy for me review your code.

**Comment by Ryosuke-Asano** [comment]
cheers your contribution 🍺!

**Review by Ryosuke-Asano — APPROVED** [review]

**Comment by TheChilledBuffalo** [comment]
> cheers your contribution 🍺!

Cheers!

**Pull request merged**
